### ISSUE TITLE
After build

### ISSUE THREAD

**Issue by mey1k** [spiegelp/MaterialDesignExtensions#100]
@spiegelp Hello master.
After build, Some strange folder(ar-DZ, cs, cs-CZ, de, fr, fr-fR ..) is created. 
Is it normal?
![build](https://user-images.githubusercontent.com/20632502/86416186-41d1aa80-bd04-11ea-8a85-454f6bdc8120.png)

**Comment by spiegelp** [comment]
@mey1k Don't worry, that's OK. The latest version adds some new translations. These folders contains the translation files for the new languages.
