### ISSUE TITLE
Provide input dialog

### ISSUE THREAD

**Issue by wdefender** [spiegelp/MaterialDesignExtensions#110]
Controls have implementations for **AlertDialog** and **ConfirmationDialog** . It would be nice to have **InputDialog**, too.

**Comment by spiegelp** [comment]
@wdefender Are you thinking of a dialog with a title and a `TextBox`?

**Comment by wdefender** [comment]
Yes, something that allows me to return input from dialogs TextBox.

**Comment by spiegelp** [comment]
@wdefender The changes are available since MaterialDesignExtensions v3.3.0.
