### ISSUE TITLE
Access remote location using OpenDirectoryControl

### ISSUE THREAD

**Issue by alex6dj** [spiegelp/MaterialDesignExtensions#116]
Is there any way to navigate a remote location folder using this control. Maybe passing the remote server name as the starting location and starting from this. Or show a list of network location like the select folder dialog from Windows OS.

The idea is to select an unknown remote folder in an uknown server.

**Comment by spiegelp** [comment]
@alex6dj The latest release features an option to set a directory via a text box. Set `SwitchPathPart = true` to enable to switch to a text box via a button on the top right corner.
