### ISSUE TITLE
TabControlStepper - Unable to set the Selected Index or Selected Item of TabControlStepper

### ISSUE THREAD

**Issue by Shreyasj96** [spiegelp/MaterialDesignExtensions#117]
Hi, I am using TabControlStepper in layout vertical mode, but if i set the selectedindex property on the TabControlStepper, nothing is happening.

**Comment by apathak31** [comment]
I am also having same problem, when I am setting the selectedindex from usercontrol, nothing happens.

**Comment by spiegelp** [comment]
@Shreyasj96 @apathak31  will be solved in the next release

**Comment by Shreyasj96** [comment]
@spiegelp Ok, Thanks.

**Comment by spiegelp** [comment]
@Shreyasj96 @apathak31 The changes are available since MaterialDesignExtensions v3.3.0.

**Comment by Shreyasj96** [comment]
Any new feature/s planned for the upcoming release?
