### ISSUE TITLE
Last Materialdesignxtension Version is not compatible with the last Materialdesigninxam version

### ISSUE THREAD

**Issue by XxQuickSilverZz** [spiegelp/MaterialDesignExtensions#121]
Last Materialdesignxtension (3.2.0 is not compatible with the last Materialdesigninxaml(3.2.0) version.
I use the tabcontrol item from Materialdesigninxaml(3.2.0) ane he dont find some styles anymore i used it.

 Because the Materialdesignthemes and colors are changed to a earlier version (2.x.x) and their dont have the styles.

Styles

Style="{StaticResource MaterialDesignNavigationRailTabItem}"> cant be find

**Comment by cjmurph** [comment]
Looks like this was addressed in commit [1b7d8872571cca8f34022058dbbb97bda1ee9ed2](https://github.com/spiegelp/MaterialDesignExtensions/commit/1b7d8872571cca8f34022058dbbb97bda1ee9ed2)

**Comment by XxQuickSilverZz** [comment]
@cjmurph  What i should do now? The version is still 3.2.0

**Comment by cjmurph** [comment]
> @cjmurph What i should do now? The version is still 3.2.0

You can wait until the next release, or clone this repo and build it yourself.

**Comment by spiegelp** [comment]
@XxQuickSilverZz Would you please try the latest prerelease v3.3.0-a01 of MaterialDesignExtensions, which uses Material Design in XAML Toolkit v3.2.0? Please let me know if your problem still exists in the prerelease v3.3.0-a01.

**Comment by XxQuickSilverZz** [comment]
@spiegelp Its published on Nuget ? 
![image](https://user-images.githubusercontent.com/55958378/99910035-33ece800-2cec-11eb-938d-2b1addcd4397.png)
Because i dont see this prerelease v3.3.0-a01.

**Comment by XxQuickSilverZz** [comment]
@spiegelp Yes it works. v3.3.0-a01 is ok and compatibel.

**Comment by XxQuickSilverZz** [comment]
@spiegelp MaterialDesignTabControl cant still be found in the prerelease
![image](https://user-images.githubusercontent.com/55958378/100018175-5f4f0000-2ddc-11eb-9f4c-e072e962a974.png)
![image](https://user-images.githubusercontent.com/55958378/100018232-70980c80-2ddc-11eb-9891-928eaf3ffe73.png)

**Comment by spiegelp** [comment]
@XxQuickSilverZz `MaterialDesignTabControl` is in all MaterialDesignExtensions versions since v2.5.0 from April 2019. I guess you have an issue with your setup. You probably forgot to add the styles to your app resources. See the lines 12 and 13 in demo's [App.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/App.xaml).

**Comment by XxQuickSilverZz** [comment]
closed.
