### ISSUE TITLE
Stepper Continue Button Disable With Validation

### ISSUE THREAD

**Issue by proxact** [spiegelp/MaterialDesignExtensions#13]
Hi, How can i disable and enable Stepper Continue button with validation? Thanks.

**Comment by spiegelp** [comment]
Hi, the API does not support that. The `StepButtonBar` is just a simple control to avoid similar code and XAML for each and every step. After long thinking, I decided to add the properties `IsBackEnabled`, `IsCancelEnabled` and `IsContinueEnabled`. You can bind whatever logic you want to them to enable or disable the buttons.

**Comment by proxact** [comment]
Thank you
