### ISSUE TITLE
Remove a tabItem from tabControl shows a binding error

### ISSUE THREAD

**Issue by beefsteak** [spiegelp/MaterialDesignExtensions#131]
![image](https://user-images.githubusercontent.com/14013918/110442565-eeff8c80-80f5-11eb-8615-396a1daf8687.png)
![image](https://user-images.githubusercontent.com/14013918/110442626-faeb4e80-80f5-11eb-9a2c-be54b45d3a40.png)
![image](https://user-images.githubusercontent.com/14013918/110442684-08083d80-80f6-11eb-8591-bd818099c569.png)
Cannot find source for binding,I guess it's a style problem.

**Comment by spiegelp** [comment]
@beefsteak Removing a tab causes a recalculation of the bindings but the parent `TabControl` is not available anymore for the tab item. That is more a problem of WPF than MaterialDesignExtensions. You might add the following code before the `Clear()` call:

```c#
foreach (object item in Tab.Items)
{
    ((TabItem)item).Template = null;
}
```
