### ISSUE TITLE
Assign a OpenFileDialog Filter in code

### ISSUE THREAD

**Issue by sebaJoSt** [spiegelp/MaterialDesignExtensions#136]
`var dialog = new MaterialDesignExtensions.Controls.OpenFileDialog(); `
`dialog.Filters = "txt files (*.txt)|*.txt|All files (*.*)|*.*";`

Error message: Cannot implicitly convert type 'string' to 'System.Collections.Generic.IList<MaterialDesignExtensions.Model.IFileFilter>'

I think I'm doing it wrong.

**Comment by spiegelp** [comment]
@sebaJoSt Assigning a string only works in XAML. In Code you can use the helper behind it like this: 
```c#
dialog.Filters = MaterialDesignExtensions.Controllers.FileFilterHelper.ParseFileFilters("txt files (*.txt)|*.txt|All files (*.*)|*.*");
```

Creating a dialog on your own is a little bit tedious. See the [demo](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/FileSystemDialogControl.xaml.cs) of the specific helper methods for ease of use.

**Comment by sebaJoSt** [comment]
Thanks for your support.  I got it working but I have another small issue:

```
OpenFileDialogArguments dialogArgs = new()
            {
                Width = 500,
                Height = 500,
                Filters = "License File|*.lic|All files (*.*)|*.*"
            };
OpenFileDialogResult dialogResult = await OpenFileDialog.ShowDialogAsync("ActivationDialog", dialogArgs);
```

The open file dialog is shown within a dialog with DialogHost "ActivationDialog". This dialog is hosted by another host (MainWIndow DialogHost) and has a size of around 200 x 200px. Even if I change the Width & Height of OpenFileDialog to larger values, it is limited to the size of the ActivationDialog. However when I wrap the OpenFileControl in a dialog user control by myself, it works.
