### ISSUE TITLE
How to align dark theme with dark theme colors from MaterialDesignInXAML?

### ISSUE THREAD

**Issue by bert2** [spiegelp/MaterialDesignExtensions#138]
I'm using the `Autocomplete` from MaterialDesignExtensions in an app using MaterialDesignInXAML. Unfortunately the colors of both dark themes do not match:

![image](https://user-images.githubusercontent.com/1454629/113506170-8b754d00-9543-11eb-89bc-25c2fbdd5469.png)

Is there a quick way to make MaterialDesignExtensions use the dark theme colors from MaterialDesignInXAML?

I could probably set the `Background` and `Foreground` on the `Autocomplete` explicitly, but that feels like working around the theming.

This is how I'm loading the styles in my `App.xaml`:

```xml
<Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <mat:BundledTheme BaseTheme="Dark" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/Generic.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/Generic.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
```

**Comment by bert2** [comment]
The workaround is the set the `Background` to `MaterialDesignPaper`:

```xml
<matex:Autocomplete
  Margin="0,16,0,0"
  AutocompleteSource="{Binding}"
  Background="{DynamicResource MaterialDesignPaper}"
  Hint="commit"
  SearchOnInitialFocus="True"
  SelectedItem="{Binding SelectedCommit, Mode=TwoWay}"
  Style="{StaticResource MaterialDesignAutocompleteDense}">
  <matex:Autocomplete.ItemTemplate>
    <DataTemplate DataType="{x:Type local:Commit_}">
      <TextBlock VerticalAlignment="Center">
        <Run FontFamily="Consolas" Text="{Binding ShortSha, Mode=OneWay}" />
        <Run Text="{Binding ShortMessage, Mode=OneWay}" />
      </TextBlock>
    </DataTemplate>
  </matex:Autocomplete.ItemTemplate>
</matex:Autocomplete>
```

**Comment by spiegelp** [comment]
@bert2 I use `MaterialDesignBackground` as background throughout the templates. It looks like that MaterialDesignInXAML tends to use `MaterialDesignPaper`. 

Setting the color via the control's color properties might be a solution, because the templates rely on them with bindings and dynamic resources. Another way is to override `MaterialDesignBackground` in your App.xaml with the desired color like this: 

```xaml
<SolidColorBrush x:Key="MaterialDesignBackground" Color="{Binding Color, Source={StaticResource MaterialDesignPaper}}" />
```

**Comment by bert2** [comment]
@spiegelp, that works too, thanks!

By the way, thank you for making it so super easy to replace those ugly default window borders 👍
