### ISSUE TITLE
Stepper, how to hide the separator ?

### ISSUE THREAD

**Issue by Coloris** [spiegelp/MaterialDesignExtensions#14]
Is it possible to hide the line separator between steps and the content area ?

![stepper](https://user-images.githubusercontent.com/5500198/41621487-c683ec5e-73da-11e8-9e1b-c50869765c69.png)

Thanks for your work !

**Comment by spiegelp** [comment]
@Coloris I defined a resource `MaterialDesignStepperSeparator` for the color. You can "hide" the separator by redefining the resource as `<SolidColorBrush x:Key="MaterialDesignStepperSeparator" Color="Transparent" />`.
