### ISSUE TITLE
Need help in changing the sidebar nav selected item background color to dark

### ISSUE THREAD

**Issue by sandeepmachiraju** [spiegelp/MaterialDesignExtensions#141]
First of all thanks to material design extensions. This library is really useful and helped me a lot in WPF development. 

Here is my question: I would like to change the background color of the selected item of sidebar-nav to dark color instead of light color. 

Is it possible? If so, can anyone guide me in doing it?  

**For reference:**
![image](https://user-images.githubusercontent.com/8036191/117906581-0be94500-b28a-11eb-8ec2-846d8013add8.png)
(I would like to change the light blue to dark blue color and the text from darkblue/black to white)

@spiegelp  @michaldivis 

Thanks

**Comment by spiegelp** [comment]
@sandeepmachiraju Use the `SelectionForeground` and `SelectionBackground` properties to set your desired colors.

**Comment by sandeepmachiraju** [comment]
@spiegelp I can able to change the color from blue to green. But it is coming as a very light color(mentioned in the above screenshot). Instead, I would like to change it to solid dark color. Should I need to change opacity?

**Comment by sandeepmachiraju** [comment]
> Thanks, @spiegelp for the quick reply. I appreciate it.
> 
> I can able to change the color from blue to green. But it is coming up as a very light color(mentioned in the above screenshot). Instead, I would like to change it to solid dark color. Should I need to change opacity? Please Let me know.

@spiegelp Is there any way that we can achieve it?

**Comment by spiegelp** [comment]
@sandeepmachiraju There is no possibility for changing the opacity at the moment. The next release features the new `SideNavigation.SelectionBackgroundOpacity` property to customize the opacity.

**Comment by sandeepmachiraju** [comment]
@spiegelp Thanks for the response. I will wait for it. :)
