### ISSUE TITLE
Broken Icons with MaterialDesignThemes 4.1.0

### ISSUE THREAD

**Issue by No1e** [spiegelp/MaterialDesignExtensions#147]
@spiegelp 

I hope you are doing well. 

I just noticed that the icons are broken when using MaterialDesignThemes 4.1.0
Here is the screenshot
![image](https://user-images.githubusercontent.com/25526781/120228759-132dbe00-c24c-11eb-8c64-fbf8413c6cfd.png)

Is this issue known? Is there fix?

Thank you and best regards,
Novak

**Comment by spiegelp** [comment]
@No1e That's a known issue if you use a newer version of MaterialDesignThemes than specified by the package (see issue #30). I did not tackle all the breaking changes since version 4.0.0 yet to be compatible.

**Comment by spiegelp** [comment]
@No1e The latest pre-release v4.0.0-a02 solves the issue.

**Comment by No1e** [comment]
@spiegelp 

Thanks for the update. Did you consider implementing fallback, to avoid such issues in the future. 
You could integrate your own set of icons (e.g. Icomoon) as a configurable fallback, in the case when the same issue comes with future releases of Material Design.

Best regards,
Nole

**Comment by sebaJoSt** [comment]
Unfortunately the icons are broken again. Is there any change you can remap the icons?
