### ISSUE TITLE
Persistentsearch as a WPFToolkit autocompletebox replacement ?

### ISSUE THREAD

**Issue by Coloris** [spiegelp/MaterialDesignExtensions#17]
So far I've been using WPF Toolkit Autocompletebox (http://www.broculos.net/2014/04/wpf-autocompletebox-autocomplete-text.html) and was wondering if It would be possible to use the persistent search control as a replacement ?

It seems that the persistentsearch control only accepts a IList<string> as a source, are you planning to extend it to support something like ObservableCollection of custom objects  (and maybe a bunch of properties like SelectedItem, SelectedValuePath, DisplayMemberPath etc.)

**Comment by spiegelp** [comment]
`PersistentSearch` is a very special use case of an autocomplete. It is not meant to handle generic output. So I am thinking of implementing another control as a generic autocomplete. Many months ago, I implemented one for a private app. However, the user interface was quite tricky. I might start to migrate the code into this open source library.

**Comment by Coloris** [comment]
That would be awesome ! WPF Toolkit Autocompletebox is kinda outdated and a real pain to style.

Thanks again for your work

**Comment by spiegelp** [comment]
@Coloris I extended the API and the templates to enable sizing. Applying the style `MaterialDesignAutocompleteDense` will render a compact `Autocomplete`. Furthermore, you can play with the `FontSize`, `Padding` and `ClearIconSize` properties and your item template to get the perfect size. 

Please let me know if the changes fit your needs.

**Comment by Coloris** [comment]
@spiegelp The compact version of AutoComplete is perfect ! I'm in the process of implementing it as a replacement of the Wpf Toolkit autocompletebox.

Here are some possible suggestions that I think would improve this control :

- A way to show the complete list of items (without having to do a first search), similar to the way it currently behaves after picking up an item and clearing it off from the list.
- Ability to decide whether or not to automatically re-open the list after clearing the selection
- Possibility to have the clear button available as soon as something is entered in the box
- For the hint, I normally use <materialDesign:HintAssist.Hint> like so :
```
                                            <materialDesign:HintAssist.Hint>
                                                <StackPanel Orientation="Horizontal" Margin="2,2,0,0">
                                                    <materialDesign:PackIcon Kind="DatabaseSearch"/>
                                                    <TextBlock>Lookup</TextBlock>
                                                </StackPanel>
                                            </materialDesign:HintAssist.Hint>
```
but it does not seem to work (or maybe there is a different way to achieve the same thing, also tried Autocomplete.Hint but it complains about not supporting StackPanel).

And a little bug : moving the MainWindow after looking for some items leaves the popup behind. I don't know how hard it is to fix, you could also auto-close the popup if the location of the MainWindow changes.

I've also noticed a little bit of lag when the popup vanished after making a selection (my list contains roughly 35 values).

Thanks again for your great work.

**Comment by uPloraX** [comment]
What about keyboard support? Up and down keys for navigation, enter and tab for selecting the selected item or something like this. Would appreciate it 👍

**Comment by Coloris** [comment]
Related to my previous suggestion: _"Ability to decide whether or not to automatically re-open the list after clearing the selection"_

I've found a buggy behavior, here is a way to reproduce it :

1. Create a tabcontrol composed of let’s say two tabitems
2. Add an autocomplete control inside each tabitems
3. Type and select something from the first autocomplete control then clear its selection
4. Switch back and forth between the second and the first tabitems, the autocomplete popup will open itself automatically without having to focus on it manually.

On a side note, I use Mahapps with MaterialDesignXaml (not for designing the controls, just the Window). Mahapps transition animation between TabItems makes it worse since the control is a bit moved, resulting in a situation where the popup end up in a different location that it should.
It is related to the fact that the popup is not attached to the control (same behavior as moving the MainWindow around while leaving the popup open).

**Comment by spiegelp** [comment]
@Coloris I just handled `Window.SizeChanged` and `Window.LocationChanged` to relocate the `Popup`. Unfortunately, `Popup` does not update its location according to its `PlacementTarget`. That's why I handle these window events to update the location.

Concerning animations you need to do some work on your own. You could try to listen to the `LayoutUpdated` event and call the `UpdatePopup` method of the `Autocomplete`. 

I will have a look at the `TabControl` issue this week.

**Comment by Coloris** [comment]
@spiegelp I've tried your implementation and it works pretty well except with double screen, here is how you can reproduce it :

Move the window while the popup is still open, as soon as the application appears on the second screen, the popup will remains stuck on the first screen until 50% of the MainWindow appears on the second screen (and then trigger the opposite effect of having the popup only on the second screen).

As for the TabControl issue, for now and until you work on it, I've implemented a dirty workaround to set the focus on the TabItem itself (which kind of fix my animation issue)

Thanks for your time.

**Comment by spiegelp** [comment]
@Coloris The issue with the tab control is a behavior of WPF. If you select a tab via mouse, WPF sets the focus to the content automatically (see [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/4cb69bd2-6dc4-43a1-a24a-6065a8bdc96b/how-to-stop-tab-control-from-automatically-setting-focus?forum=wpf)). So you need to keep your workaround. 

The behavoir of the autocomplete popup is caused by WPF too. The popup of a MaterialDesignTheme combo box behaves the same. It will be never cut by screen edges: 

![2018-08-11_21-53_1](https://user-images.githubusercontent.com/6129929/43995887-f404fb6c-9db7-11e8-854e-1792d8d4fd81.png)

At the moment, I don't know how to resolve the issues.

**Comment by spiegelp** [comment]
@Coloris I changed the behavior of the autocomplete popup with the last commit. The control loses the focus causing the popup to close. Now its behavior is more close to a combobox.
