### ISSUE TITLE
Stepper in Xaml

### ISSUE THREAD

**Issue by manuelheld** [spiegelp/MaterialDesignExtensions#2]
Hallo,
erstmals vielen Dank für die Extension. Finde ich wirklich klasse. 
Ich hab nur eine Frage wegen dem Stepper.
ist es möglich die einzelnen Stepper per XAML anzulegen ?
`   <ScrollViewer Grid.Row="1" HorizontalAlignment="Stretch" HorizontalScrollBarVisibility="Disabled" VerticalAlignment="Stretch" VerticalScrollBarVisibility="Auto">
            <controls:Stepper HorizontalAlignment="Stretch" IsLinear="{Binding Path=IsLinear}" Layout="{Binding Path=Layout}"  VerticalAlignment="Stretch" >
                <controls:Stepper.Steps>
                    
                </controls:Stepper.Steps>
            </controls:Stepper>
        </ScrollViewer>`

So ungefähr ?

Danke

**Comment by spiegelp** [comment]
Das funktioniert momentan noch nicht. Ich werde es ins nächste Release aufnehmen. 

**In English:** 
Stepper does not support setting the steps via XAML yet. This feature is scheduled for the next release. 

**Example out of the demo:**
```
<controls:Stepper IsLinear="{Binding Path=IsLinear}" Layout="{Binding Path=Layout}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
    <model:Step>
        <model:Step.Header>
            <model:StepTitleHeader FirstLevelTitle="What is a Stepper?" />
        </model:Step.Header>
        <model:Step.Content>
            <viewModel:StepperTutorialOneViewModel />
        </model:Step.Content>
    </model:Step>
    <model:Step>
        <model:Step.Header>
            <model:StepTitleHeader FirstLevelTitle="Layout and navigation" />
        </model:Step.Header>
        <model:Step.Content>
            <viewModel:StepperTutorialTwoViewModel />
        </model:Step.Content>
    </model:Step>
    <model:Step>
        <model:Step.Header>
            <model:StepTitleHeader FirstLevelTitle="Steps" SecondLevelTitle="Header and content" />
        </model:Step.Header>
        <model:Step.Content>
            <viewModel:StepperTutorialThreeViewModel />
        </model:Step.Content>
    </model:Step>
    <model:Step>
        <model:Step.Header>
            <model:StepTitleHeader FirstLevelTitle="Validation" />
        </model:Step.Header>
        <model:Step.Content>
            <viewModel:StepperTutorialFourViewModel />
        </model:Step.Content>
    </model:Step>
</controls:Stepper>
```
