### ISSUE TITLE
OpenDirectoryDialog.ShowDialogAsync bug

### ISSUE THREAD

**Issue by devriesb13** [spiegelp/MaterialDesignExtensions#21]
Hi There,

First of all, thanks for a great extension. I have found a bug using the OpenDirectoryDialog.ShowDialogAsync method. Its seems to crash when you set the CurrentDirectory property with a directory that contains no sub folders. When you add a dummy sub folder, the method does not crash. 

  var options = new OpenDirectoryDialogArguments()
            {
                ShowHiddenFilesAndDirectories = true,
                ShowSystemFilesAndDirectories = true,
                CurrentDirectory = VM.OutputDirectory,
                Height = 500
            };

Cheers

**Comment by spiegelp** [comment]
@devriesb13 If the initial current directory is empty, WPF does not initialize the `ScrollViewer` inside the `ItemsControl`. I fix this situation by checking for a null reference.
