### ISSUE TITLE
AutoComplete Activation Indicator

### ISSUE THREAD

**Issue by Imadlekal** [spiegelp/MaterialDesignExtensions#25]
Is it possible to remove the Activation indicator that shows under the text you write?

![image](https://user-images.githubusercontent.com/14929605/50350083-2f3aba80-053e-11e9-979f-4f5bedae6236.png)

**Comment by spiegelp** [comment]
@Imadlekal There is no API to control that. The `Autocomplete` uses a style out of [Material Design in XAML Toolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) for the `TextBox`. You just need to define a new `ControlTemplate` for the `Underline` inside your `Autocomplete`. The following snippet renders the `Underline` as a `Border` width no size: 

```XAML
<!-- namespace definitions -->
xmlns:wpfLib="http://materialdesigninxaml.net/winfx/xaml/themes"
xmlns:controls="clr-namespace:MaterialDesignExtensions.Controls;assembly=MaterialDesignExtensions"

<!-- add a ControlTemplate to Underlune inside the Autocomplete.Resources -->
<controls:Autocomplete>
    <controls:Autocomplete.Resources>
        <Style TargetType="{x:Type wpfLib:Underline}">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type wpfLib:Underline}">
                        <Border Width="0" Height="0" />
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </controls:Autocomplete.Resources>
</controls:Autocomplete>
```
