### ISSUE TITLE
[REQUEST] Add "Create New Folder" option in FileControl/Dialogs

### ISSUE THREAD

**Issue by wjax** [spiegelp/MaterialDesignExtensions#32]
Hello.

I miss that super useful function to be able to create a folder within the File/Folder Control/Dialogs.

Thanks!

**Comment by spiegelp** [comment]
@wjax Thank you for the feature request. I will consider it for a future release.

**Comment by spiegelp** [comment]
@wjax The next release is going to add a new property `CreateNewDirectoryEnabled`. Set it to `true` for showing a button in the upper left corner of the control.
