### ISSUE TITLE
Stepper doesn't work in colorzone or in Dialogs(MaterialDesignDialogHost)

### ISSUE THREAD

**Issue by speedyalibaba** [spiegelp/MaterialDesignExtensions#36]
Unfortunatly the stepper foreground and when hovering the hover-color are not corectly set when the stepper is inside a colorzone from MaterialDesignInXamlToolkit:
![image](https://user-images.githubusercontent.com/35242690/55648051-83ad3180-57df-11e9-9b55-a61c182c6dfb.png)

Something simmilar happens when the stepper is inside a materialDesign-Dialog and the App is set to dark (the dialog is always in light mode):
![image](https://user-images.githubusercontent.com/35242690/55648197-f3bbb780-57df-11e9-94c2-0438d03ceb63.png)

It seems that the stepper is somehow always using the application colors.

**Comment by spiegelp** [comment]
@speedyalibaba There is a quite easy trick for your special requirements: Reference the theme with the desired colors inside your `Stepper` control. 

```xaml
<controls:Stepper>
    <controls:Stepper.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />
                 <!-- or -->
                 <!--<ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />-->
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </controls:Stepper.Resources>
</controls:Stepper>
```

**Comment by speedyalibaba** [comment]
@spiegelp Thank you very much. Helped me a lot :)
