### ISSUE TITLE
How to properly use the Stepper

### ISSUE THREAD

**Issue by AmitBhatnagar24** [spiegelp/MaterialDesignExtensions#4]
How do I know when I have arrived to the next step?

The continue navigation event occurs before the Step is actually selected giving a chance to cancel it.. but how do I know when I have arrived at a step!?

Why no binding to SelectedStep (which gets its value after navigation is complete)

Please help.. I am struggling with this :/

**Comment by spiegelp** [comment]
Hi, are you looking for an event saying "now I am showing the next step"? Such an event does not exist yet but I will add a `StepChanged` event to my ToDo list. 

The `Stepper` has a property `Controller` which exposes `ActiveStep`. This property always contains the current step, because the UI binds to it. I am thinking of exposing a `ActiveStep` property directly on the `Stepper`. Or you might want listen to the `PropertyChanged` event of the controller and check the arguments for the `ActiveStep` property name.

**Comment by AmitBhatnagar24** [comment]
>are you looking for an event saying "now I am showing the next step"? 

Not an event, but rather a `SelectedStep` binding, (like a tab control has `SelectedItem`), which then my ViewModel would know when we have actually reached that step. I need to do this because when I reach a certain step, I need to perform some calculations. Right now I have to do some ugly code-behind inspection on the prev/next steps to see when I am about to reach the step in question.

>I am thinking of exposing a ActiveStep property directly on the Stepper

exactly what I would be looking for.

**Comment by AmitBhatnagar24** [comment]
Also, how do I know when the Continue / Finish button is clicked - can I bind to that specific button's `Command` ?

**Comment by spiegelp** [comment]
Hi, based on your feedback, I added the following members to the Stepper API:
* read-only `ActiveStep` property
* event `ActiveStepChangedEvent`
* command properties for navigation callbacks
  * `ActiveStepChangedCommand`
  * `BackNavigationCommand`
  * `CancelNavigationCommand`
  * `ContinueNavigationCommand`
  * `StepNavigationCommand`

You can assign your custom command to these new command properties. According well-tried events already exist. The changes will be scheduled for the next release.

**Comment by AmitBhatnagar24** [comment]
I'm again adding to this now closed issue because I still feel that I don't know exactly to handle the validation, A new issue is not required. 

When I have a 2 Step stepper with BlockNavigationOnValidationErrors set to true. I have derived from Step to allow for validation as per the documents. If I reach step 2 and it fails validation.. why would it prevent me from going back a step? I feel that the BlockNavigationOnValidationErrors should only restrict going to the next step. 

How can I accomplish this with the already implemented validation and events/commands already in play?
