### ISSUE TITLE
Unable to change OpenFileDialog colors

### ISSUE THREAD

**Issue by Gigas002** [spiegelp/MaterialDesignExtensions#40]
I'm using **2.6.0** version from NuGet. I have the following color scheme in my `App.xaml`:
```xaml
<!-- Material Design Extensions -->
<ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/Generic.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />
<!--  Material Design  -->
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Dark.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Cyan.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Teal.xaml" />
```

The application looks as it should:
![image](https://user-images.githubusercontent.com/24297712/60018498-2f09ac00-9694-11e9-89cc-3a15fb6125be.png)

But the dialogs are light colored:
![image](https://user-images.githubusercontent.com/24297712/60018519-40eb4f00-9694-11e9-999e-ee00db44c5e3.png)

The same behavior is for `OpenDirectoryDialog` and `SaveFileDialog`.

Is there any way to use the same color scheme for them, as the application uses?

**Comment by spiegelp** [comment]
@Gigas002 The `DialogHost` of Material Design in XAML uses its own theme. You need to set the theme on your instance. 
```xaml
<md:DialogHost Identifier="dialogHost" DialogTheme="Dark">
...
</md:DialogHost>
```

**Comment by Gigas002** [comment]
Thanks, that worked out.
