### ISSUE TITLE
OpenFileDialog doesn't have "Create new directory" button

### ISSUE THREAD

**Issue by Gigas002** [spiegelp/MaterialDesignExtensions#42]
When trying to initialize `OpenFileDialog` like this:

```c#
await OpenFileDialog.ShowDialogAsync("DialogHost",
          new OpenFileDialogArguments {CreateNewDirectoryEnabled = true});
```
It doesn't create **Create new directory** button on dialog.
Using this property when initializing `OpenDirectoryDialog` and `SaveFileDialog` works as expected.

**Comment by spiegelp** [comment]
@Gigas002 The `CreateNewDirectoryEnabled` does not make any sense for the `OpenFileControl` and `OpenFileDialog` controls. A new directory cannot contain any files to open yet. That's why I omit the button on these two controls. I will update the API documentation with a notice on that.
