### ISSUE TITLE
SideNavigation Dark Theme Font is not eye friendly.

### ISSUE THREAD

**Issue by dicksonpun** [spiegelp/MaterialDesignExtensions#44]
![image](https://user-images.githubusercontent.com/1645523/61178354-6e535a80-a5b9-11e9-9785-2d57c36a467a.png)
![image](https://user-images.githubusercontent.com/1645523/61178357-7a3f1c80-a5b9-11e9-94f7-81c26f0ff9af.png)

Is there a way to make the text "pop" more in dark mode?

**Comment by dicksonpun** [comment]
![image](https://user-images.githubusercontent.com/1645523/61178743-71eadf80-a5c1-11e9-9024-d284633ecca9.png)

I ended up figuring a workaround. I wrapped the SideNav using a ColorZone. Hope it helps others!

**Comment by dicksonpun** [comment]
Actually I'm going to re-open this issue for visibility for a real fix.
This workaround is only for color zones of Light (lesser of 2 evils but also unusable for bright primaries like yellow and lime) and PrimaryLight (barely usable) . All other combinations are unusable.

**Comment by spiegelp** [comment]
@dicksonpun As I understand your posts, you need other colors for the text and highlight border to get more contrast. Try to set the `SelectionForeground`, `SelectionBackground` and `NavigationItemFeedback` properties of the `SideNavigation`. 

Please let me know if this solves your issue.

**Comment by dicksonpun** [comment]
Thanks for the prompt response.  This partially addresses my issue.  It helps address the colors regarding the selected item.  The part I'm still having a roadblock on is how to set the unselected/unselectable items like unselected FirstLevelNavigationItems and SubheaderNavigationItems. Any ideas?
![image](https://user-images.githubusercontent.com/1645523/61186417-1bb68480-a633-11e9-97be-1b97400b7e35.png)

**Comment by spiegelp** [comment]
@dicksonpun The `SideNavigation` looks fine in the demo app. The templates use dynamic resources as the foreground, which will be set inside the specific theme resource dictionary. 

I think that something in your app setup or control styles messes up the text block foreground. You might have a conflicting style definition in your app. Do you have an own definition for `MaterialDesignNavigationItemSubheader` or `MaterialDesignNavigationItemText`? Do you use the predefined classes for the items or do you use any custom classes implementing the necessary interface? 

If you do not find any problems on your own, could you please attach a sample project with the reproduced behavior? I can do a much better analysis with the full source code.

**Comment by dicksonpun** [comment]
> I think that something in your app setup or control styles messes up the text block foreground. You might have a conflicting style definition in your app.

Ahh I think that sounds very plausible. 

I was referencing [this github project (Bachup)](https://github.com/ChrisStayte/Bachup) for the style and themes in [my learning demo project](https://github.com/dicksonpun/PANDA/).  I wonder if the way this project implemented the style conflicts/overrides the predefined settings.  

I've since switched to using the ColorTool example in the MaterialDesignInXamlToolkit for in my non-learning project (not public on Github unfortunately).  I haven't had a chance to experiment with the SideNavigation with the ColorTool in that project yet.  

Not-related but kinda, something I did notice was that the dark modes seem different between these Demos and I'm not sure why: 
![image](https://user-images.githubusercontent.com/1645523/61677740-a865e000-acce-11e9-879f-91dd0a76a446.png)

If you don't mind taking a quick look see if anything sticks out to you in [my demo project](https://github.com/dicksonpun/PANDA/), I'd appreciate it.  Please let me know if I goofed up the settings, I'd be interested in learning what I did wrong. Thanks!

**Comment by spiegelp** [comment]
@dicksonpun The dark modes look different because of a different brush for the background. Material Design Extensions uses `Background="{DynamicResource MaterialDesignBackground}"` while Material Design in XAML uses `Background="{DynamicResource MaterialDesignPaper}"` instead. Both projects define the background in their `MainWindows.xaml`. 

I was very busy the last two weeks. I hope that I can have a deeper look into your demo project this week.

**Comment by spiegelp** [comment]
@dicksonpun 

* Your configuration seems to be fine.
* I would remove the `ColorZone` from inside the drawer, because it is a temporary hack solution. 
* If you are having problems with colors, it is usually an issue with conflicting resources. Just try to add the desired theme resources into the problematic control's resources. See [StepperControl.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/StepperControl.xaml) line 102 of the demo for an example.

**Comment by dicksonpun** [comment]
Thank you for looking at this issue.  Your recent comments helped point me in the right direction.
I ended up figuring out how to properly resolve this issue, in case you were interested.

**App.xaml**
As it turns out I did not include the DarkTheme counterpart in the MergedDictionary section.  Even when I did, (you may already know this) it appears as though the ResourceDictionary is loaded in sequential order such that it favors the last loaded item. 

_**CASE 1 (DarkTheme is loaded first, followed by LightTheme)**_
As you can see the LightTheme looks great, and the DarkTheme not so much.
![image](https://user-images.githubusercontent.com/1645523/62827310-77285380-bb9a-11e9-9ff8-69dca6322ceb.png)
![image](https://user-images.githubusercontent.com/1645523/62827322-e1d98f00-bb9a-11e9-86e6-402f886f445d.png)
![image](https://user-images.githubusercontent.com/1645523/62827324-eef67e00-bb9a-11e9-8e34-c513fbff6065.png)

_**CASE 2 (LightTheme is loaded first, followed by DarkTheme)**_
As you'd expect the observed pattern is consistent here.
![image](https://user-images.githubusercontent.com/1645523/62827346-6f1ce380-bb9b-11e9-8024-fcc4804794f9.png)
![image](https://user-images.githubusercontent.com/1645523/62827374-06823680-bb9c-11e9-8c4a-838b2d703007.png)
![image](https://user-images.githubusercontent.com/1645523/62827369-f66a5700-bb9b-11e9-8875-c51227698ab5.png)

_**SOLUTION!**_
**App.xaml**
Only add either the LightTheme or DarkTheme ResourceDictionary.
![image](https://user-images.githubusercontent.com/1645523/62827386-36c9d500-bb9c-11e9-9c82-ea612c23c114.png)

**<Whatever file/function is handling the Theme switch event>**
Add logic to update the ResourceDictionary before setting the Theme.  Someone smarter than me can probably optimize it but for now... it works!
![image](https://user-images.githubusercontent.com/1645523/62827458-44cc2580-bb9d-11e9-9b16-54e8eb10e1db.png)
![image](https://user-images.githubusercontent.com/1645523/62827463-63322100-bb9d-11e9-90bf-c3548baab6f1.png)
![image](https://user-images.githubusercontent.com/1645523/62827472-78a74b00-bb9d-11e9-8f78-a8c47146ea27.png)
