### ISSUE TITLE
Language output

### ISSUE THREAD

**Issue by seanmars** [spiegelp/MaterialDesignExtensions#45]
Why always generate the `uz-Latn-UZ` and `de` dll? How to disable that?

**Comment by spiegelp** [comment]
@seanmars 

1. The resource files are necessary for the file system controls. I do not like to make different builds with and without localization support. It will be confusing and the next issue asks why the user interface is not in German like the demo app. 

2. The .csproj file lists resources and build actions for them. It is a XML file so you can open it with any text editor. You may conditionally include or exclude the files from the build, if a specified symbol is set inside the build configuration. Please look for tutorials on conditional builds.

**Comment by SupunSam** [comment]
Yes. It's too many unnecessary Folders. Just Include this in your CSProj File.

```
<PropertyGroup>   
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
</PropertyGroup>
```
