### ISSUE TITLE
OpenFileDialog - Select mutiple files

### ISSUE THREAD

**Issue by JackDaniel91** [spiegelp/MaterialDesignExtensions#46]
Hi,

is it possible to select multiple files in the FileDialog?

If not, can this request be included as feature request for a future release?

Many thanks

**Comment by spiegelp** [comment]
@JackDaniel91 The file system controls and dialogs only support the selection of one file or dictionary. I might consider your request for a new featured control.

**Comment by spiegelp** [comment]
@JackDaniel91 Please check out the latest release and try the `OpenMultipleFilesControl` and `OpenMultipleFilesDialog` controls.

**Comment by JackDaniel91** [comment]
Cool, I'll try it tomorrow! Thanks!!
