### ISSUE TITLE
Stepper vertical alignment stretch doesn't work as expected

### ISSUE THREAD

**Issue by Awsmolak** [spiegelp/MaterialDesignExtensions#47]
I have a stepper hosted in a DockPanel with LastChildFill = true. The stepper does, in fact, inherit the available height within the DockPanel. However, when VerticalAlignment is set to stretch the content is not given the remaining space in the grid, the remaining space is filled below the back/continue buttons. (ie. Top and Stretch look the same except that with stretch the height of the stepper is set correctly.)

Is there a way to make the stepper content fill all available vertical space in its parent?

**Comment by spiegelp** [comment]
@Awsmolak Are you using a horizontal stepper? The latest commit should fix your issue.

**Comment by Awsmolak** [comment]
That seems to have fixed it!

**Comment by spiegelp** [comment]
@Awsmolak I published a prerelease with the fix some moments ago.
