### ISSUE TITLE
TabStripPlacement proerty of TabControl doesn't work

### ISSUE THREAD

**Issue by Awsmolak** [spiegelp/MaterialDesignExtensions#48]
The TabStripPlacement property doesn't seem to work. This prevents you from using tabs on the bottom, left or right.

**Comment by michaldivis** [comment]
I'm experiencing the same problem.

**Comment by Awsmolak** [comment]
I implemented a fix...seems to work alright. 

@michaldivis I'll fork the project and do a pull request. That way you can use it. I'll post a link when I have it up.

**Comment by Awsmolak** [comment]
This works:
https://github.com/Awsmolak/MaterialDesignExtensions/tree/ImplementTabStripPlacement

**Comment by michaldivis** [comment]
@Awsmolak thank you, sir!

**Comment by spiegelp** [comment]
solved with pull request #49
