### ISSUE TITLE
OpenFileDialog

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [spiegelp/MaterialDesignExtensions#5]
develop OpenFileDialog  Extension filter....

**Comment by spiegelp** [comment]
Hi, I recently thought about that and will focus on it later. At the moment I am refactoring the controls because the `ListBox` raises multiple `SelectionChanged` events (well known issue in WPF). After that I will have some time for the filter feature.

**Comment by spiegelp** [comment]
The upcoming release features `Filters` and `FilterIndex` properties. A filter can be assigned via string similar to the [.NET API](https://docs.microsoft.com/de-de/dotnet/api/microsoft.win32.filedialog.filter?view=netframework-4.7.1#Microsoft_Win32_FileDialog_Filter).

**Comment by jigneshBadrakhiya** [comment]
thnaks
