### ISSUE TITLE
MaterialWindow.ResizeMode bug

### ISSUE THREAD

**Issue by Gigas002** [spiegelp/MaterialDesignExtensions#50]
Hello. Just reporting a little issue with `MaterialWindow.ResizeMode` (xaml code). If it's values set to `NoResize` everything works as expected, no **Minimize** and **Full Screen** buttons, window is not resizable:
![image](https://user-images.githubusercontent.com/24297712/64079619-6b8c0080-ccf2-11e9-837b-a915998ef007.png)

But when it's set to `CanMinimize` (which usually has **Close** and **Minimize** buttons only, the **Full Screen** button is still on place and makes the application full screen:
![image](https://user-images.githubusercontent.com/24297712/64079642-a8f08e00-ccf2-11e9-9938-398e8120a251.png)

I'm using **2.8.0-a01** version.

**Comment by spiegelp** [comment]
@Gigas002 The improved behavior of the caption buttons according to the [API doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.resizemode?view=netframework-4.8) will be in the next release.
