### ISSUE TITLE
Stepper - highlight finished step with check-icon

### ISSUE THREAD

**Issue by TheWurstbrot** [spiegelp/MaterialDesignExtensions#53]
Currently, there is no way to highlight a  finished step with a "check-icon", right? 
(see example from [material.io archive](https://material.io/archive/guidelines/components/steppers.html#steppers-types-of-steps) below)

I am using a linear, horizontal stepper and would love to indicate that step no. 1 is done, if step no. 2 is currently active.

![image](https://user-images.githubusercontent.com/25752416/65133326-b308d100-da02-11e9-9a10-ccfdd10c8f3a.png)

**Comment by spiegelp** [comment]
@TheWurstbrot I'm having an idea for a clean solution for this feature. However it might introduce a breaking change. I will consider the feature along other breaking changes for an upcoming v3.0.0 release.

**Comment by TheWurstbrot** [comment]
Great!

**Comment by enrmadriv** [comment]
I upgraded the NuGet Package to v 2.8.0 but I can't implement DoneIconTemplate yet.

**Comment by spiegelp** [comment]
@enrmadriv The new properties will be available with release v3.0.0.

**Comment by spiegelp** [comment]
@TheWurstbrot I did a pre-release with the new feature some moments ago. Please check it out to see if it fits your needs.
