### ISSUE TITLE
.Net Core 3.0

### ISSUE THREAD

**Issue by Gaz83** [spiegelp/MaterialDesignExtensions#54]
Can you add support for .Net Core 3.0?

Material Design xaml toolkit work fine but the extensions require the full .net framework >= 4.5.

**Comment by spiegelp** [comment]
@Gaz83 I decided to support .NET Core 3 as I heard of Microsoft's future plans for .NET earlier this year. I will wait for a final release of Material Design in XAML Toolkit supporting .NET Core 3 before I start the porting of Material Design Extensions.

**Comment by Maruhl** [comment]
[Version 3.0](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases/tag/v3.0.0) is released with .Net Core 3 support.

**Comment by Maruhl** [comment]
.Net Core 3.0 makes the library 'Pri.LongPath' obsolete. Simple test in my fork seem to confirm this.

**Comment by Lorymi** [comment]
@Gaz83 any news??

**Comment by spiegelp** [comment]
Great to hear that MaterialDesignThemes  3.0.0 is final. I will resolve the breaking changes and implement support for .NET Core 3 sometime around the holidays.

**Comment by spiegelp** [comment]
First pre-release with .NET Core 3 support out now!

**Comment by spiegelp** [comment]
Final v3.0.0 release with .NET Core 3 support out now!
