### ISSUE TITLE
Double clicking on a file closes OpenFileDialog and SaveFileDialog selecting the file

### ISSUE THREAD

**Issue by glen-yb** [spiegelp/MaterialDesignExtensions#57]
Like the Windows file dialogs, OpenFileDialog and SaveFileDialog should return when a file is double clicked. The dialogs should also select a file when you hit Enter and cancel when you hit Escape.

**Comment by spiegelp** [comment]
@glen-yb I will consider your feedback for a future release.

**Comment by spiegelp** [comment]
@glen-yb Please have a look at the latest preview release. It contains improved keyboard navigation for the file sytem controls.

**Comment by glen-yb** [comment]
@spiegelp Thank you! Your solution is very elegant.

**Comment by pialin** [comment]
I found that OpenFileDialog is still working in a "single click" way. Wasn't it supposed to be solved? @spiegelp please help me. My code was listed below. Thanks!
```csharp
OpenFileDialogArguments dialogArgs = new OpenFileDialogArguments();
OpenFileDialogResult result = await ShowDialogAsync("RootDialog", dialogArgs);
```
