### ISSUE TITLE
Can't seem to style PersistentSearch very well

### ISSUE THREAD

**Issue by michaldivis** [spiegelp/MaterialDesignExtensions#59]
Hello,

I love what you've done with these controls so far, however, I'm having a hard time making the PersistentSearch control fit my design, since it's pretty big compared to my other Material Design controls. For some reason, changing the FontSize, Padding and Margin does nothing. I've also looked up other issues in this repo and found that the Autocomplete control has a "Dense" style that can be applied to make it smaller. From what I can tell from the theme XAML, the PersistentSearch only has one style. 

**Is there any way I can make the PersistentSearch smaller or better yet, apply another style?**

I apologise if this question is stupid and has an easy solution.
Keep up the good work! Michal

**Comment by michaldivis** [comment]
I've created a pull request #60 to solve this.

**Comment by spiegelp** [comment]
@michaldivis Please try the latest preview release. It contains your changes for a dense style. Furthermore, I added an `IconSize` property to `PersistentSearch` and set a reasonable value for it in the dense style.
