### ISSUE TITLE
Dynamically create StepButtonBar

### ISSUE THREAD

**Issue by enrmadriv** [spiegelp/MaterialDesignExtensions#61]
I'm implementing your stepper controll on my project. 

I need to create a my custom StepButtonBar depending of some binding data. I'm trying to create the StepButtonBar object but can't figure out how to add it to Step interface.

I will appreciate your help.

**Comment by spiegelp** [comment]
@enrmadriv I would suggest to place your button bar inside the template for the step. There you could use a `ContentControl` with a `TemplateSelector` or implement your own converters to control the visibiliy of controls depending on your binding data.

**Comment by enrmadriv** [comment]
I will try it. Your project are awesome

Thanks for your suggestions 👍
