### ISSUE TITLE
Get the validation state of a control in a stepper data template inside ViewModel

### ISSUE THREAD

**Issue by WaffleBuffer** [spiegelp/MaterialDesignExtensions#66]
I wanted to know if it was possible to get the validation state of control (such as textbox) which is located inside the Datatemplate of Step inside its ViewModel.
This is with the scenario of having some ValidationRules on the TextBox and trying to synchronize them with the HasValidationError of the Step.

**Comment by enrmadriv** [comment]
You can add HasError property to the ViewModel of your step, do your validation and assign the result to this property. Then use Validate method provided by StepperControl to notice the change. 

I achieve something similar.

**Comment by WaffleBuffer** [comment]
That's what i have done in the end ^^.
Sorry i forgot to update this issue.
