### ISSUE TITLE
Material Emoji

### ISSUE THREAD

**Issue by jvcmd** [spiegelp/MaterialDesignExtensions#68]
@spiegelp  Can you implement this? for MaterialDesignExtensions
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1567

**Comment by spiegelp** [comment]
@jvcmd The emoji font used by Google is not supported on windows. See the [website](https://www.google.com/get/noto/help/emoji/): "_This font format is supported on Android and Linux, but doesn’t work on macOS or Windows._". 

I was thinking of adding emojis to an app a longer time ago, but I never found a suitable free emoji font. If you find one, you could create your own default styles for the controls based upon the material styles of the libraries.
