### ISSUE TITLE
DialogBox

### ISSUE THREAD

**Issue by maxmontgmx** [spiegelp/MaterialDesignExtensions#70]
Hi all,

does it exist a simple DialogBox with standard buttons (OK, Cancel, Yes, No, ...) like Winform DialogBox to display a simple message?

Thanks

**Comment by spiegelp** [comment]
@maxmontgmx There are no styles or templates for such kind of dialog boxes. I might consider this for a future release.

**Comment by spiegelp** [comment]
@maxmontgmx The next release features an `AlertDialog` and a `ConfirmationDialog` control.

**Comment by maxmontgmx** [comment]
@spiegelp I would like to popup a confirmation dialog box in modal mode (which is blocking), not in async mode. How can I do?
Thanks for your help

**Comment by NormskiJJO** [comment]
MyDialog dialog = new Dialogs.MyDialog();
            dialog.Owner = Application.Current.MainWindow;
            dialog.WindowStartupLocation = WindowStartupLocation.CenterOwner;
            dialog.ShowDialog();

**Comment by maxmontgmx** [comment]
@spiegelp it's not possible to use AlertDialog or ConfirmationDialog for that? Thanx
