### ISSUE TITLE
Path field

### ISSUE THREAD

**Issue by maxmontgmx** [spiegelp/MaterialDesignExtensions#72]
Hi all,

Does it exist a textbox component for path (directory or file) edition?
I imagine a textbox with a button which open a file browser...
Thanks

**Comment by spiegelp** [comment]
@maxmontgmx There is not such a control. I will consider it for a future release.

**Comment by spiegelp** [comment]
@maxmontgmx You're looking for a control like this?

![TextBoxOpenDirectory1](https://user-images.githubusercontent.com/6129929/76161402-88870d80-6133-11ea-9a3b-d6b75968c4ae.png)

A click on the folder icon opens an according dialog for selecting a directory or file. I just implemented a version for selecting a directory. Versions for opening and saving a file will follow.

**Comment by spiegelp** [comment]
@maxmontgmx The latest pre-release v3.1.0-a03 features the controls `TextBoxOpenDirectory`, `TextBoxOpenFile` and `TextBoxSaveFile`.

**Comment by spiegelp** [comment]
@maxmontgmx Get the latest final release v3.1.0.

**Comment by maxmontgmx** [comment]
@spiegelp Thanks for your support. In my own Control, I had used material designtextbox (with HelperText feature). In yours, I don't see this feature.

**Comment by spiegelp** [comment]
@maxmontgmx I just added the `TextBoxFileSystemPath.TextBoxStyle` property to enable a custom style for the `TextBox`. Please have a look at [TextBoxFileSystemPathsControl.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/TextBoxFileSystemPathsControl.xaml) line 39 for an code example.
