### ISSUE TITLE
MaterialWindow - WindowStyle is completely ignored

### ISSUE THREAD

**Issue by Maruhl** [spiegelp/MaterialDesignExtensions#74]
Please provide the same functionality:

https://docs.microsoft.com/en-US/dotnet/api/system.windows.window.windowstyle?view=netframework-4.8

**Comment by spiegelp** [comment]
@Maruhl Windows are hardly mentioned in the Material Design specification. I will think of a Material Design alike look for the different `WindowStyle` options.

**Comment by spiegelp** [comment]
@Maruhl The latest prerelease implements different looks for `WindowStyle`.
