### ISSUE TITLE
MaterialWindow TitleDataTemplate

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [spiegelp/MaterialDesignExtensions#75]
If possible, add a TitleDataTemplate for MaterialWindow. Sometimes it’s convenient to have some other buttons in the window title (for example, settings) for quick access.
![image](https://user-images.githubusercontent.com/29563929/75804703-81f24200-5d91-11ea-84a4-4d164165e529.png)
You have an awesome library. I really lacked the implementation of these elements in the Material style. Thanks you

**Comment by spiegelp** [comment]
@AgPeHaJIuH1 I was thinking of adding buttons to the title bar some months ago. I will schedule this feature for a future release.

**Comment by spiegelp** [comment]
@AgPeHaJIuH1 You may check out the latest prerelease to see the new property in action. See the `MainWindow` of the demo for an example.
