### ISSUE TITLE
Add XmlnsDefinition

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [spiegelp/MaterialDesignExtensions#76]
It would be nice to add XmlnsDefinition and put all the namespaces from your library there for easy access in xaml (for example, as implemented in MaterialDesingThemes xmlns:mat ="http://materialdesigninxaml.net/winfx/xaml/themes")

[assembly: XmlnsPrefix("http://materialdesigninxaml.net/winfx/xaml/themes", "materialDesign")]
[assembly: XmlnsDefinition("http://materialdesigninxaml.net/winfx/xaml/themes", "MaterialDesignThemes.Wpf")]
[assembly: XmlnsDefinition("http://materialdesigninxaml.net/winfx/xaml/themes", "MaterialDesignThemes.Wpf.Transitions")]
[assembly: XmlnsDefinition("http://materialdesigninxaml.net/winfx/xaml/themes", "MaterialDesignThemes.Wpf.Converters")]

P.S. only make the XmlnsPrefix shorter, for example "matEx"

**Comment by spiegelp** [comment]
@AgPeHaJIuH1 `xmlns:mde="https://spiegelp.github.io/MaterialDesignExtensions/winfx/xaml"` will be available with the upcoming release v3.3.0
