### ISSUE TITLE
MaterialDesignStepNumberIconTemplate' resource not found.

### ISSUE THREAD

**Issue by eiredrake** [spiegelp/MaterialDesignExtensions#77]
2.8.0 does't have this problem but updating to the 3.0 version the design panel posts an immediate error. If you actually run the app with it, the MaterialDesignStepNumberIconTemplate' resource not found exception crashes the app.

Presumably this resource was originally inside the 2.8.0 package and was either renamed or moved in 3.0 so i'd need to include wherever this reference is but i don't know where or what it's attached to.

Stacktrace:

  at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by spiegelp** [comment]
@eiredrake The resource `MaterialDesignStepNumberIconTemplate` was introduced with v3.0.0. I guess you are missing the resource from the file `StepperTemplates.xaml`. Please try to add the following resource dictionary: 

```C#
<ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/StepperTemplates.xaml" />
```

If you still get the problem, please post the full stack trace and your App.xaml.

**Comment by eiredrake** [comment]
Nope that did it. Thanks a lot!
