### ISSUE TITLE
Reguest

### ISSUE THREAD

**Issue by NormskiJJO** [spiegelp/MaterialDesignExtensions#87]
Brilliant Extension to Material Design WPF.
How about a general material design MessageBox?

**Comment by ahmedflix25** [comment]
https://github.com/denpalrius/Material-Message-Box

**Comment by spiegelp** [comment]
@NormskiJJO You might be looking for `AlertDialog` or `ConfirmationDialog` ([example in demo](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/MessageDialogControl.xaml.cs)).
