### ISSUE TITLE
AppBar AppIcon

### ISSUE THREAD

**Issue by NormskiJJO** [spiegelp/MaterialDesignExtensions#88]
Can the AppBar AppIcon  support material design pack icons?

**Comment by spiegelp** [comment]
@NormskiJJO The `AppBar.AppIcon` property is of type `object`. So it can be whatever you like.

**Comment by NormskiJJO** [comment]
How would you set it? i.e. 
<AppBar.AppIcon>
<materialDesign:PackIcon Kind="Magnify" Opacity=".56" />
<AppBar.AppIcon>

**Comment by spiegelp** [comment]
```xml
<mde:AppBar Title="My app">
    <mde:AppBar.AppIcon>
        <md:PackIcon Kind="Volleyball" Width="24" Height="24" />
    </mde:AppBar.AppIcon>
</mde:AppBar>
```

**Comment by NormskiJJO** [comment]
Thanks!
