### ISSUE TITLE
Is it possible for Stepper to navigate steps programmatically?

### ISSUE THREAD

**Issue by OscarFather** [spiegelp/MaterialDesignExtensions#9]
For example, there are five steps and current active step is 1, i want to navigate to step 2 programmatically.
Is is possible?

**Comment by OscarFather** [comment]
@spiegelp Thanks~

**Comment by Coloris** [comment]
Could you provide an example while using XAML ? From my viewmodel I have no reference to the controller :-/

**Comment by spiegelp** [comment]
@Coloris  Take a look at [StepperTemplates.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensions/Themes/StepperTemplates.xaml) line 450. The buttons in the template bind their `Command` property to commands of `Stepper` to trigger navigation: `Command="{x:Static controls:Stepper.ContinueCommand}"`.

**Comment by Coloris** [comment]
What if I want to go back to the first step by setting a property (just like a tabitem), I don't get how to bind to a Static property from my view model

**Comment by spiegelp** [comment]
Do you like to set the current step via a data binding? There is an `ActiveStep` property, but it is readonly. It could be extended with a setter, to accomplish something like this: 
```c#
<materialDesignExtensions:Stepper ActiveStep="{Binding Path=MyViewModel.StepToShow}">
```
Are you looking for this?

**Comment by Coloris** [comment]
Yes, just like a tabitem, you can bind a property to change from viewmodel the current tab (since it's an index)
