### ISSUE TITLE
No method to close or clear the current entry in the autocomplete box?

### ISSUE THREAD

**Issue by forensicmike** [spiegelp/MaterialDesignExtensions#93]
I've reviewed the source/demo and can't seem to find a way to programmatically clear the autocomplete box. Would be great to have a way to do this.

**Comment by spiegelp** [comment]
@forensicmike The next release is going to feature a `ClearSelection()` method. 

As a temporary solution you can set the `SelectedItem` and `SearchTerm` properties to `null`.
