### ISSUE TITLE
OpenDirectoryControl

### ISSUE THREAD

**Issue by mey1k** [spiegelp/MaterialDesignExtensions#99]
![dialog](https://user-images.githubusercontent.com/20632502/86318029-db994900-bc6b-11ea-9d54-a69fa3de4103.png)

Images appear strange. Why?

**Comment by CorradoBarbero** [comment]
Which images? In which sense "strange"?

**Comment by spiegelp** [comment]
@mey1k I guess you are using MaterialDesignThemes 3.1.1 or higher. Every icon set update in MaterialDesignThemes causes a break in MaterialDesignExtensions (I skip the technical details). Please get the latest MaterialDesignExtensions v3.2.0 to fix your issue.

**Comment by mey1k** [comment]
@spiegelp 
It work! Thank you.!
